language: csharp
mono: none
dotnet: 1.0.1
sudo: required
dist: trusty
# dotnet: 1.0.0-preview2-003121

# branches:
#   only:
#   - master

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - powershell

# before_script:
#   - powershell --version

script:
  powershell scripts/build.ps1

after_script:
  powershell scripts/publish.ps1